"""Configuration management for OmaAura."""

import os
import tomllib
from pathlib import Path
from typing import Any, Dict

DEFAULT_CONFIG: Dict[str, Any] = {
    "hardware": {
        "gpu_backend": "ene_i2c",        # "ene_i2c", "openrgb", or "none"
        "gpu_i2c_bus": "/dev/i2c-1",
        "gpu_i2c_addr": 0x67,
        "motherboard_backend": "openrgb", # "openrgb" or "none"
        "openrgb_devices": "all",         # "all" or list of device IDs like [0, 1]
    },
    "theme": {
        "sync_mode": "accent",            # "accent" or "wallpaper"
        "calibrate_led": True,            # Boosts saturation/value so LEDs match the swatch
        "saturation_floor": 1.0,         # Minimum HSV saturation sent to hardware
        "value_target": 1.0,              # Target HSV value (brightness) for hardware
        "fallback_color": "89b4fa",       # Catppuccin Blue / Omarchy default
    },
    "service": {
        "enabled": True,
        "poll_interval_sec": 2.0,
    },
}


def get_config_dir() -> Path:
    xdg_config = os.environ.get("XDG_CONFIG_HOME")
    if xdg_config:
        base = Path(xdg_config)
    else:
        base = Path.home() / ".config"
    return base / "omaaura"


def get_config_path() -> Path:
    return get_config_dir() / "config.toml"


def load_config() -> Dict[str, Any]:
    path = get_config_path()
    if not path.exists():
        return DEFAULT_CONFIG.copy()

    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        merged = DEFAULT_CONFIG.copy()
        for section, values in data.items():
            if isinstance(values, dict) and section in merged and isinstance(merged[section], dict):
                merged[section] = {**merged[section], **values}
            else:
                merged[section] = values
        return merged
    except Exception:
        return DEFAULT_CONFIG.copy()


def _format_toml_value(val: Any) -> str:
    if isinstance(val, bool):
        return "true" if val else "false"
    elif isinstance(val, int):
        return f"0x{val:02x}" if val in (0x67, 0x68) else str(val)
    elif isinstance(val, float):
        return str(val)
    elif isinstance(val, str):
        return f'"{val}"'
    elif isinstance(val, list):
        items = ", ".join(_format_toml_value(item) for item in val)
        return f"[{items}]"
    return f'"{val}"'


def save_config(config: Dict[str, Any]) -> Path:
    config_dir = get_config_dir()
    config_dir.mkdir(parents=True, exist_ok=True)
    path = get_config_path()

    lines = [
        "# OmaAura Configuration File",
        "# Automatically generated by 'omaaura setup'",
        "",
    ]

    for section_name, section_dict in config.items():
        if isinstance(section_dict, dict):
            lines.append(f"[{section_name}]")
            for key, val in section_dict.items():
                lines.append(f"{key} = {_format_toml_value(val)}")
            lines.append("")

    content = "\n".join(lines).strip() + "\n"
    path.write_text(content, encoding="utf-8")
    return path
